package dev.kage.manager.core

import android.content.Context
import dev.kage.common.Crypto
import dev.kage.common.Protocol
import java.io.File

/**
 * Everything about getting the privileged side running.
 *
 * The server is a dex executed with app_process, so the app itself cannot start it (starting it
 * needs adb or root). What the app can do is make that one command as short and as stable as
 * possible: it extracts the dex and writes a start script whose contents never change between
 * runs, so the user only ever copies one line once.
 */
object Starter {

    const val NICE_NAME = "kage_server"
    const val MAIN_CLASS = "dev.kage.server.KageServer"

    data class Paths(
        val sharedDir: File,
        val dex: File,
        val script: File,
        val runtimeDir: String,
    )

    /** Copies the server dex out of the assets and rewrites the start script. */
    fun prepare(context: Context, token: String, debug: Boolean = false, logLevel: String = "info"): Paths {
        val external = context.getExternalFilesDir(null) ?: context.filesDir
        val shared = File(external, "kage")
        shared.mkdirs()
        File(shared, Protocol.DIR_REQUESTS).mkdirs()
        File(shared, Protocol.DIR_RESPONSES).mkdirs()
        File(shared, Protocol.DIR_OUTPUT).mkdirs()

        val dex = File(shared, "server.dex")
        writeIfChanged(dex, context.assets.open("server.dex").readBytes())

        val runtime = Protocol.RUNTIME_DIR
        val script = File(shared, Protocol.START_SCRIPT)
        writeIfChanged(script, scriptBody(context.packageName, dex.absolutePath, shared.absolutePath, runtime, token, debug, logLevel).toByteArray())

        return Paths(shared, dex, script, runtime)
    }

    /**
     * The one-liner the user has to run through adb. Deliberately references the script file so
     * that reinstalling the app (new dex, new token) does not invalidate what they already copied
     * into their terminal history.
     */
    fun adbCommand(paths: Paths): String = "adb shell sh ${paths.script.absolutePath}"

    /** Alternative for a rooted device. */
    fun rootCommand(paths: Paths): String = "su -c \"sh ${paths.script.absolutePath}\""

    /** Direct command, useful when the script cannot be read (custom ROMs, secondary users). */
    fun manualCommand(paths: Paths, token: String): String =
        "adb shell \"CLASSPATH=${paths.dex.absolutePath} app_process /system/bin --nice-name=$NICE_NAME $MAIN_CLASS " +
            "--token=$token --shared=${paths.sharedDir.absolutePath} --runtime=${paths.runtimeDir}\""

    /** Same as [manualCommand] but usable from a terminal emulator app on the device itself. */
    fun onDeviceCommand(paths: Paths, token: String): String =
        "CLASSPATH=${paths.dex.absolutePath} /system/bin/app_process /system/bin --nice-name=$NICE_NAME $MAIN_CLASS " +
            "--token=$token --shared=${paths.sharedDir.absolutePath} --runtime=${paths.runtimeDir}"

    private fun scriptBody(
        packageName: String,
        dex: String,
        shared: String,
        runtime: String,
        token: String,
        debug: Boolean,
        logLevel: String,
    ): String = """
        #!/system/bin/sh
        # Kage start script - generated by the Kage app, do not edit.
        # Run it with:  adb shell sh "$shared/${Protocol.START_SCRIPT}"
        # or on a rooted device:  su -c "sh $shared/${Protocol.START_SCRIPT}"

        DEX="$dex"
        SHARED="$shared"
        RUNTIME="$runtime"
        TOKEN="$token"
        LOG_LEVEL="$logLevel"
        PACKAGE="$packageName"
        SERVER_LOG="$'$'SHARED/${Protocol.FILE_SERVER_LOG}"

        if [ ! -f "$'$'DEX" ]; then
          echo "Kage: server dex missing at $'$'DEX - open the app once to extract it"
          exit 1
        fi

        # Android 14+ refuses to load a writable dex through app_process
        SDK=$'$'(getprop ro.build.version.sdk)
        if [ "$'$'SDK" -ge 34 ]; then
          if [ -w "$'$'DEX" ]; then
            echo "Kage: removing write permission from the dex (Android 14+)"
            chmod 400 "$'$'DEX"
          fi
          if [ -w "$'$'DEX" ]; then
            echo "Kage: cannot make $'$'DEX read-only, copy it to /data/local/tmp and retry"
            exit 1
          fi
        fi

        mkdir -p "$'$'RUNTIME"
        mkdir -p "$'$'SHARED/req" "$'$'SHARED/res" "$'$'SHARED/out"

        # only one server at a time
        if [ -f "$'$'RUNTIME/server.pid" ]; then
          OLD=$'$'(cat "$'$'RUNTIME/server.pid")
          if [ -n "$'$'OLD" ] && kill -0 "$'$'OLD" 2>/dev/null; then
            echo "Kage: server already running (pid $'$'OLD), stopping it first"
            kill "$'$'OLD" 2>/dev/null
            sleep 1
          fi
        fi

        echo "Kage: starting server as uid $'$'(id -u) ..."
        echo "$'$'SERVER_LOG" > /dev/null 2>&1

        exec /system/bin/app_process \
          -Djava.class.path="$'$'DEX" \
          -Dkage.library.path="$'$'SHARED" \
          /system/bin \
          --nice-name=$NICE_NAME \
          $MAIN_CLASS \
          --token="$'$'TOKEN" \
          --shared="$'$'SHARED" \
          --runtime="$'$'RUNTIME" \
          --log="$'$'LOG_LEVEL" ${if (debug) "--debug" else ""}
    """.trimIndent()

    private fun writeIfChanged(file: File, bytes: ByteArray) {
        if (file.exists() && file.length() == bytes.size.toLong() && file.readBytes().contentEquals(bytes)) return
        file.writeBytes(bytes)
        runCatching { file.setExecutable(true, false) }
    }

    fun isAlive(context: Context): Boolean {
        val external = context.getExternalFilesDir(null) ?: context.filesDir
        val status = File(File(external, "kage"), Protocol.FILE_STATUS)
        return status.exists() && System.currentTimeMillis() - status.lastModified() < 6000
    }

    fun token(context: Context): String {
        val prefs = context.getSharedPreferences("kage", Context.MODE_PRIVATE)
        val stored = prefs.getString("token", null)
        if (stored != null && stored.length == 64) return stored
        val token = Crypto.randomToken(32)
        prefs.edit().putString("token", token).apply()
        return token
    }

    fun serverLog(context: Context): String {
        val external = context.getExternalFilesDir(null) ?: context.filesDir
        val log = File(File(external, "kage"), Protocol.FILE_SERVER_LOG)
        return if (log.exists()) log.readText().takeLast(20000) else ""
    }
}
